import { describe, it, expect, vi, beforeEach } from 'vitest';
import api from '../api/axios';
import { 
  getSuppliers, 
  getSupplier, 
  createSupplier, 
  updateSupplier, 
  deleteSupplier, 
  getNextSupplierCode 
} from '../api/suppliers';
import { SupplierPayload } from '../types/supplier';
import { en } from '../i18n/en';
import { bn } from '../i18n/bn';

describe('Supplier Form Validation & Payload Modeling', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('validates minimum required supplier payload', () => {
    const payload: SupplierPayload = {
      name: 'Rahim Textile Mills Ltd.',
      supplier_code: 'SUP-0001',
      status: 'ACTIVE',
      opening_balance: 0,
      credit_limit: 50000,
      payment_terms: 'Net 30 Days',
    };

    expect(payload.name).toBe('Rahim Textile Mills Ltd.');
    expect(payload.status).toBe('ACTIVE');
    expect(payload.credit_limit).toBe(50000);
    expect(payload.payment_terms).toBe('Net 30 Days');
  });

  it('correctly handles contact and location details in supplier payload', () => {
    const payload: SupplierPayload = {
      name: 'Apex Footwear Ltd.',
      contact_person: 'Mr. Rafiqul Islam',
      mobile: '+880 1712-345678',
      email: 'sales@apex.com',
      address: 'Plot 12, Tejgaon I/A',
      city: 'Dhaka',
      country: 'Bangladesh',
      tax_number: 'BIN-9928374-01',
      opening_balance: 15000,
      credit_limit: 100000,
      status: 'ACTIVE',
    };

    expect(payload.contact_person).toBe('Mr. Rafiqul Islam');
    expect(payload.city).toBe('Dhaka');
    expect(payload.opening_balance).toBe(15000);
    expect(payload.tax_number).toBe('BIN-9928374-01');
  });

  it('normalizes empty opening balance and credit limit to 0', () => {
    const rawOpeningBalance: number | '' = '';
    const rawCreditLimit: number | '' = '';

    const normalizedOpening = rawOpeningBalance === '' ? 0 : Number(rawOpeningBalance);
    const normalizedCredit = rawCreditLimit === '' ? 0 : Number(rawCreditLimit);

    expect(normalizedOpening).toBe(0);
    expect(normalizedCredit).toBe(0);
  });

  it('enforces required supplier_code generated by system with unique non-duplicate pattern', () => {
    const payload: SupplierPayload = {
      name: 'Delta Garments Ltd',
      supplier_code: 'SUP-0001',
      status: 'ACTIVE',
    };

    expect(payload.supplier_code).toBeDefined();
    expect(payload.supplier_code).toMatch(/^SUP-\d{4,}$/);
    expect(payload.supplier_code!.length).toBeGreaterThan(0);
  });

  it('validates unique sequential code generation without duplicates', () => {
    const existingCodes = new Set(['SUP-0001', 'SUP-0002', 'SUP-0003']);
    
    let counter = 1;
    let candidate = `SUP-${String(counter).padStart(4, '0')}`;
    while (existingCodes.has(candidate)) {
      counter++;
      candidate = `SUP-${String(counter).padStart(4, '0')}`;
    }

    expect(candidate).toBe('SUP-0004');
    expect(existingCodes.has(candidate)).toBe(false);
  });

  it('calls backend API getSuppliers directly', async () => {
    const mockResponse = {
      success: true,
      data: [
        { id: 1, supplier_code: 'SUP-0001', name: 'Vendor One', status: 'ACTIVE' },
      ],
    };
    vi.spyOn(api, 'get').mockResolvedValueOnce({ data: mockResponse });

    const result = await getSuppliers({ all: true });
    expect(api.get).toHaveBeenCalledWith('/suppliers', { params: { all: true } });
    expect(result.data).toHaveLength(1);
  });

  it('calls backend API getSupplier by ID', async () => {
    const mockSupplier = { id: 3, supplier_code: 'SUP-0003', name: 'Vendor Three' };
    vi.spyOn(api, 'get').mockResolvedValueOnce({ data: { success: true, data: mockSupplier } });

    const result = await getSupplier(3);
    expect(api.get).toHaveBeenCalledWith('/suppliers/3');
    expect(result.data.name).toBe('Vendor Three');
  });

  it('calls backend API getNextSupplierCode', async () => {
    vi.spyOn(api, 'get').mockResolvedValueOnce({
      data: { success: true, data: { supplier_code: 'SUP-0009' } },
    });

    const result = await getNextSupplierCode();
    expect(api.get).toHaveBeenCalledWith('/suppliers/next-code');
    expect(result.data.supplier_code).toBe('SUP-0009');
  });

  it('calls backend API createSupplier', async () => {
    const payload: SupplierPayload = {
      name: 'Fresh Fruits Ltd',
      supplier_code: 'SUP-0010',
      status: 'ACTIVE',
    };
    vi.spyOn(api, 'post').mockResolvedValueOnce({
      data: { success: true, data: { id: 10, ...payload } },
    });

    const result = await createSupplier(payload);
    expect(api.post).toHaveBeenCalledWith('/suppliers', payload);
    expect(result.data.id).toBe(10);
  });

  it('calls backend API updateSupplier to toggle status', async () => {
    vi.spyOn(api, 'put').mockResolvedValueOnce({
      data: { success: true, data: { id: 10, status: 'INACTIVE' } },
    });

    const result = await updateSupplier(10, { status: 'INACTIVE' });
    expect(api.put).toHaveBeenCalledWith('/suppliers/10', { status: 'INACTIVE' });
    expect(result.data.status).toBe('INACTIVE');
  });

  it('calls backend API deleteSupplier', async () => {
    vi.spyOn(api, 'delete').mockResolvedValueOnce({
      data: { success: true, message: 'Supplier deleted successfully' },
    });

    const result = await deleteSupplier(10);
    expect(api.delete).toHaveBeenCalledWith('/suppliers/10');
    expect(result.success).toBe(true);
  });

  it('verifies 100% i18n key parity between en.ts and bn.ts for suppliers', () => {
    const suppKeysEn = Object.keys(en).filter((k) => k.startsWith('suppliers.'));
    const suppKeysBn = Object.keys(bn).filter((k) => k.startsWith('suppliers.'));

    expect(suppKeysEn.length).toBeGreaterThan(15);
    expect(suppKeysBn.length).toBe(suppKeysEn.length);

    suppKeysEn.forEach((key) => {
      expect(key in bn).toBe(true);
      expect((bn as any)[key]).toBeTruthy();
      expect(typeof (bn as any)[key]).toBe('string');
    });
  });
});
